@startuml desarrollo_implementacion
package "  "  as usantatecla.mastermind {
}
package "  "  as usantatecla.mastermind.controllers {
}
package "  "  as usantatecla.mastermind.models {
}
package "  "  as usantatecla.mastermind.views {
}
package "  "  as usantatecla.mastermind.views.console {
}
package "  "  as usantatecla.mastermind.views.graphics {
}
package "  "  as usantatecla.utils {
}
package "  "  as java.io {
}
package "  "  as java.util {
}

[mastermind.jar] as jar

jar *--> usantatecla.mastermind
jar *--> usantatecla.mastermind.controllers
jar *--> usantatecla.mastermind.models
jar *--> usantatecla.mastermind.views
jar *--> usantatecla.mastermind.views.console
jar *--> usantatecla.mastermind.views.graphics
jar *--> usantatecla.utils
jar *--> java.io
jar *--> java.util
@enduml

@startuml despliegue_fisica
node node #DDDDDD [
<b>Personal Computer</b>
----
]

[ mastermind.jar ] as component

node *--> component
@enduml