@startuml arquitectura
package usantatecla.mastermind #DDDDDD { }
usantatecla.mastermind .down.> usantatecla.mastermind.views.console
usantatecla.mastermind .down.> usantatecla.mastermind.views.graphics
usantatecla.mastermind .down.> usantatecla.mastermind.models

package usantatecla.mastermind.views #DDDDDD { }
usantatecla.mastermind.views .down.> usantatecla.mastermind.models
usantatecla.mastermind.views .down.> usantatecla.mastermind.types

package usantatecla.mastermind.models #DDDDDD { }
usantatecla.mastermind.models .down.> usantatecla.mastermind.types
package usantatecla.mastermind.types #DDDDDD { }
package java.util{ }
usantatecla.mastermind.models .down.> java.util

package usantatecla.utils #DDDDDD { }
package java.io{ }
usantatecla.utils .down.> java.io

package usantatecla.mastermind.views.console #DDDDDD { }
usantatecla.mastermind.views.console .down.> usantatecla.mastermind.models
usantatecla.mastermind.views.console .down.> usantatecla.mastermind.types
usantatecla.mastermind.views.console .down.> usantatecla.utils
usantatecla.mastermind.views.console .down.> usantatecla.mastermind.views

package usantatecla.mastermind.views.graphics #DDDDDD { }
package java.awt{ }
package java.awt.event{ }
package javax.swing{ }
usantatecla.mastermind.views.graphics .down.> usantatecla.mastermind.views
usantatecla.mastermind.views.graphics .down.> usantatecla.mastermind.models
usantatecla.mastermind.views.graphics .down.> usantatecla.mastermind.types
usantatecla.mastermind.views.graphics .down.> java.awt
usantatecla.mastermind.views.graphics .down.> java.awt.event
usantatecla.mastermind.views.graphics .down.> javax.swing

@enduml
