@startuml arquitectura
package usantatecla.mastermind #DDDDDD { }
usantatecla.mastermind .down.> usantatecla.mastermind.views
usantatecla.mastermind .down.> usantatecla.mastermind.models

package usantatecla.mastermind.models #DDDDDD { }
usantatecla.mastermind.models .down.> usantatecla.mastermind.types
package usantatecla.mastermind.types #DDDDDD { }
package java.util{ }
usantatecla.mastermind.models .down.> java.util

package usantatecla.utils #DDDDDD { }
package java.io{ }
usantatecla.utils .down.> java.io

package usantatecla.mastermind.views #DDDDDD { }
usantatecla.mastermind.views .down.> usantatecla.mastermind.models
usantatecla.mastermind.views .down.> usantatecla.mastermind.types
usantatecla.mastermind.views .down.> usantatecla.utils
@enduml
